### ISSUE TITLE
Output path options not working

### ISSUE THREAD

**Issue by FStefanni** [clenemt/docdash#89]
Hi,

it seems the following three options are not working properly:
```
scopeInOutputPath: [false|true], // Add scope from package file (if present) to the output path, true by default.
nameInOutputPath: [false|true], // Add name from package file to the output path, true by default.
versionInOutputPath: [false|true] // Add package version to the output path, true by default. 
```

I am trying to create the output in a directory, namely "public", without the subpath "@mygroup/myproject/1.0.0".
From the documentation, I understand the previous three options should do the trick, by setting them to false.
Unfortunately, this is not the case.

I am using jsdoc 3.6.5 and docdash 1.2.0.

Regards.

**Comment by walkermatt** [comment]
It looks as though the changes to add those options haven't been released yet.

The [v1.2.0 release was made 2020-01-26](https://github.com/clenemt/docdash/commit/cc438657fa37c4a3c60c7ad4a4dc9ec871cd081c) while the PR to add those options [was merged 2020-02-04](https://github.com/clenemt/docdash/pull/78).

While waiting for a new release you can always install direct from GitHub if you're happy with the risk of using an unreleased version:
```shell
npm i https://github.com/clenemt/docdash#a4b9401a3fbe811b4e162c8c90232e2b789efe4b --save-dev
```

I've specified the most recent commit as the commits since the last release all look fine to me.

**Comment by ar2rsawseen** [comment]
Will release 2.0.0 soon
